title: "Your Name"
name: "Your Name"
description: "Researcher • Wireless / AI / Communications"
url: "https://YOUR-USERNAME.github.io"   # ← change to your username
baseurl: ""

# Theme
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
minimal_mistakes_skin: "default"   # "air", "aqua", "contrast", "dark", "dirt", "neon", "plum", "sunrise"

# Build settings
markdown: kramdown
permalink: /:categories/:title/
paginate: 5
paginate_path: /blog/page:num/

# GitHub Pages-supported plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-include-cache

# Include custom page folder
include:
  - _pages

# Author profile (shows on home & sidebar)
author:
  name: "Your Name"
  avatar: "/assets/img/profile.jpg"         # add your image here (optional)
  bio: "Grad researcher exploring semantic communication, DeepJSCC, and wireless systems."
  location: "Huntsville, AL"
  links:
    - label: "Email"
      icon: "fas fa-envelope"
      url: "mailto:you@example.com"
    - label: "Google Scholar"
      icon: "ai ai-google-scholar"
      url: "https://scholar.google.com/"
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/YOUR-USERNAME"
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://www.linkedin.com/in/YOUR-LINK/"
    - label: "CV"
      icon: "far fa-file"
      url: "/cv.pdf"

# Footer links
footer:
  links:
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/YOUR-USERNAME"
    - label: "X (Twitter)"
      icon: "fab fa-x-twitter"
      url: "https://x.com/YOUR-USERNAME"

# Navigation (header) uses _data/navigation.yml
collections:
  posts:
    output: true
    permalink: /blog/:title/
